os: linux
dist: focal
language: python
cache: pip
arch:
  - s390x
  - ppc64le
  - arm64

python:
    - "3.9"

env:
    - AVOCADO_PARALLEL_LINT_JOBS=1

addons:
  apt:
    packages:
    - enchant
    - hunspell-en-us
    - golang

install:
    - git clone https://github.com/avocado-framework/avocado-result-html optional_plugins/html
    - pip install -r requirements-selftests.txt

script:
    - make check
