os: linux
dist: focal
language: python
cache: pip
arch:
  - s390x

python:
    - "3.9"

install:
    - pip install -r requirements-dev.txt
    - python3 setup.py develop --user

script:
    - python3 selftests/check.py --select unit
