os: linux
dist: focal
language: python
cache: pip
arch:
  - s390x
  - ppc64le
  - arm64

python:
    - "3.9"

env:
    - AVOCADO_PARALLEL_LINT_JOBS=1

addons:
  apt:
    packages:
    - enchant
    - hunspell-en-us
    - golang

install:
    - pip install -r requirements-selftests.txt

script:
    - python -c "import multiprocessing; print(multiprocessing.cpu_count())"
    - python -c "import platform; print(platform.machine())"
    - make check
